spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:


  mail:
    host: smtp.gmail.com
    port: 587
    username: arslan321asyanov@gmail.com
    password: ikwasyzypufljgrb
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        hbm2ddl:
          auto: validate
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  sql:
    init:
      mode: always


bot:
  recountNewArticleFixedRate: 20000
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
